### ISSUE TITLE
Server wont start using dedicated lua server

### ISSUE THREAD

**Issue by Meganium97** [evilfactory/LuaCsForBarotrauma#102]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Trying to start a server ends up in a file not found error

### Reproduction steps

1. Try to start server using dedicated server executable

### Bug prevalence

Happens every time I play

### Version

Other

### -

Using 0.18.15.0 build with lua from this repo

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 08/17/2022 15:07:22)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


0222435A485FA40E56BEE1E7CEB05961


Game version 0.18.15.0 (ReleaseLinux, branch master, revision d73a8ac)
Graphics mode: 2560x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla, Barotronics - The Turret Collection, Hazardous Reactors + advanced medecin/neurotrauma patch, Hazardous Reactors, Let Them All In, EK | Gunnery, Genes+ Revived and Expanded, Enhanced Armaments Neurotrauma Patch, Neurotrauma Cybernetics, NT Surgery Plus, Neurotrauma, DynamicEuropa, Improved Husks, Barotraumatic Xanmonsters1 Fixes, Barotraumatic Undersea Horrors Fixes, BaroTraumatic, Enhanced Armaments, New Wrecks For Barotrauma (With sellable wrecks), EK | Utility, Submarine Weapon Sound Makeover, ExtendedMonsters [Spawner Edition], #5-16 TITAN, MGE Posters, Lua For Barotrauma, EK | Dockyard, Performance Fix, ES Guppy
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen


System info:
    Operating system: Unix 5.19.1.1 64 bit
    GPU name: 
    Display mode: {Width:2560 Height:1080 Format:Color AspectRatio:2.3703704}
    GPU status: Normal


Exception: ChildServerRelay readTask did not run to completion: status was WaitingForActivation. (System.Exception)
Target site: Int32 ReadIncomingMsgs()
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Networking/ChildServerRelay.cs:line 141
   at Barotrauma.Networking.ChildServerRelay.<UpdateRead>g__readBytes|40_0(Span`1 readTo) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Networking/ChildServerRelay.cs:line 172
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Networking/ChildServerRelay.cs:line 183
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()


Last debug messages:
[08/17/2022 15:07:22] Exiting...
[08/17/2022 15:07:07] Failed to start server {No such file or directory}
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Barotrauma.Networking.ChildServerRelay.Start(ProcessStartInfo processInfo) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/ChildServerRelay.cs:line 29
   at Barotrauma.MainMenuScreen.StartServer() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/MainMenuScreen.cs:line 934
[08/17/2022 15:07:07] Failed to start ChildServerRelay Process. File: .//home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2559634234/Binary/DedicatedServer.exe, arguments: -name "Server" -public False -playstyle Casual -banafterwrongpassword False -karmaenabled True -maxplayers 10 -nopassword -steamid 76561198872612173 -ownerkey 211832184 -pipes 250 254
[08/17/2022 15:06:31] Loading texture from stream failed! {Error loading texture data from stream: unknown image type    at MonoGame.Utilities.ImageReader.Read(Stream stream, Int32& x, Int32& y, Int32& comp, Int32 req_comp) in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Utilities\Imaging\ImageReader.cs:line 56
   at Microsoft.Xna.Framework.Graphics.Texture2D.TextureDataFromStream(Stream stream, Int32& width, Int32& height, Int32& channels) in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.cs:line 313}
   at Microsoft.Xna.Framework.Graphics.Texture2D.TextureDataFromStream(Stream stream, Int32& width, Int32& height, Int32& channels) in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.cs:line 313
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Utils/TextureLoader.cs:line 241

Inner exception: unknown image type
   at MonoGame.Utilities.ImageReader.Read(Stream stream, Int32& x, Int32& y, Int32& comp, Int32 req_comp) in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Utilities\Imaging\ImageReader.cs:line 56
   at Microsoft.Xna.Framework.Graphics.Texture2D.TextureDataFromStream(Stream stream, Int32& width, Int32& height, Int32& channels) in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.cs:line 313
[08/17/2022 15:06:05] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:06:05] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:06:05] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:06:05] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:06:05] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:06:05] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:06:05] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:06:05] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:06:05] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:06:05] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:06:05] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:06:05] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:05:53] Overriding an affliction or a buff with the identifier 'huskinfection' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2085783214/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'combatstimulant' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'implacable' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'concussion' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'drunk' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'invertcontrols' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'chemwithdrawal' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'chemaddiction' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'opiatewithdrawal' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'opiateaddiction' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'burn' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'explosiondamage' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'organdamage' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'gunshotwound' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'bitewounds' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'lacerations' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'internaldamage' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'bleedingnonstop' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'bleeding' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'bloodloss' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:51] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:05:48] Overriding an affliction or a buff with the identifier 'nausea' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:05:48] Duplicate affliction: 'burningrod' defined in Affliction of '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:05:48] Duplicate affliction: 'criticalrod_burn_emitter' defined in Affliction of '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:05:48] Duplicate affliction: 'burn_emitter_rod' defined in Affliction of '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:05:48] Duplicate affliction: 'burn_emitter' defined in Affliction of '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:05:48] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:05:48] Duplicate affliction: 'dnadamage' defined in Affliction of '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:05:48] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2655920928/afflictionpatch.xml'
[08/17/2022 15:05:28] Attempting to open ALC device "Built-in Audio Analog Stereo"
[08/17/2022 15:05:26] Logged in as Meganium97 (SteamID STEAM_1:1:456173222)
```

**Comment by evilfactory** [comment]
the error suggests that it's caused by some broken texture? i suggest trying to start it without any mods but this one

**Comment by Meganium97** [comment]
With only Lua For Barotrauma (and performance fix)

`Barotrauma Client crash report (generated on 08/17/2022 15:23:02)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


0222435A485FA40E56BEE1E7CEB05961


Game version 0.18.15.0 (ReleaseLinux, branch master, revision d73a8ac)
Graphics mode: 2560x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla, Lua For Barotrauma, Performance Fix
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen


System info:
    Operating system: Unix 5.19.1.1 64 bit
    GPU name: 
    Display mode: {Width:2560 Height:1080 Format:Color AspectRatio:2.3703704}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Dispose(Boolean)
Stack trace: 
   at Microsoft.Xna.Framework.Game.Dispose(Boolean disposing) in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 111
   at Microsoft.Xna.Framework.Game.Dispose() in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 99
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59


Last debug messages:
[08/17/2022 15:23:02] Exiting...
[08/17/2022 15:22:47] Failed to start server {No such file or directory}
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Barotrauma.Networking.ChildServerRelay.Start(ProcessStartInfo processInfo) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/ChildServerRelay.cs:line 29
   at Barotrauma.MainMenuScreen.StartServer() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/MainMenuScreen.cs:line 934
[08/17/2022 15:22:47] Failed to start ChildServerRelay Process. File: .//home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2559634234/Binary/DedicatedServer.exe, arguments: -name "Server" -public False -playstyle Casual -banafterwrongpassword False -karmaenabled True -maxplayers 10 -nopassword -steamid 76561198872612173 -ownerkey 1776132945 -pipes 250 254
[08/17/2022 15:18:42] Alc.CaptureOpenDevice attempt 1 failed: error code 40964
[08/17/2022 15:15:23] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:15:23] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:15:23] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:15:23] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:15:23] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:15:23] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:15:23] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:15:23] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:15:23] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:15:23] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:15:23] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:15:23] WARNING: /home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2197353935/randomevents_campaign.xml: All root EventSets should have an identifier
[08/17/2022 15:15:12] Overriding an affliction or a buff with the identifier 'huskinfection' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2085783214/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'combatstimulant' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'implacable' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'concussion' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'drunk' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'invertcontrols' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'chemwithdrawal' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'chemaddiction' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'opiatewithdrawal' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'opiateaddiction' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'burn' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'explosiondamage' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'organdamage' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'gunshotwound' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'bitewounds' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'lacerations' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'internaldamage' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'bleedingnonstop' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'bleeding' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'bloodloss' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:09] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[08/17/2022 15:15:05] Overriding an affliction or a buff with the identifier 'nausea' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:15:05] Duplicate affliction: 'burningrod' defined in Affliction of '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:15:05] Duplicate affliction: 'criticalrod_burn_emitter' defined in Affliction of '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:15:05] Duplicate affliction: 'burn_emitter_rod' defined in Affliction of '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:15:05] Duplicate affliction: 'burn_emitter' defined in Affliction of '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:15:05] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:15:05] Duplicate affliction: 'dnadamage' defined in Affliction of '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Content/Items/Medical/Afflictions.xml'
[08/17/2022 15:15:05] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file '/home/ianl/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2655920928/afflictionpatch.xml'
[08/17/2022 15:14:45] Attempting to open ALC device "Built-in Audio Analog Stereo"
[08/17/2022 15:14:44] Logged in as Meganium97 (SteamID STEAM_1:1:456173222)
`

**Comment by evilfactory** [comment]
oh wait just noticed you are using Linux, are you using the workshop content package? because for Linux you gotta do the manual installation

**Comment by Meganium97** [comment]
I did.

**Comment by evilfactory** [comment]
Are you using the Lua server executable or the vanilla? you are supposed to use the vanilla if you installed manually

**Comment by Meganium97** [comment]
Lua server executable?

**Comment by evilfactory** [comment]
yep

**Comment by Meganium97** [comment]
I got it to run, but it ran the server really badly, it was running like 1 frame per 15 seconds. This was on the server lobby, by the way.

**Comment by Meganium97** [comment]
Anyways, it worked, but now it's complaining I'm lualess in the server.

**Comment by evilfactory** [comment]
what did you do to install the mod

**Comment by Meganium97** [comment]
I followed your instructions and also did what you told me for my last issue.

**Comment by evilfactory** [comment]
which ones? i think you only did the client ones, but not the server ones (Installing to existing Server and Installing to existing Client)

**Comment by Meganium97** [comment]
ah, yeah I probably only did the client
