### ISSUE TITLE
Self hosting server on Linux leads to crash

### ISSUE THREAD

**Issue by Michael-Nunley** [evilfactory/LuaCsForBarotrauma#123]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Using Linux, when starting a server from the in game GUI, after choosing the LuaForBarotrauma server file and pressing start, the program will hang, render an error then crash.

### Reproduction steps

1. Use a linux distribution
2. Manually install this mod
3. Launch game using native files, not via proton
4. Open Host Server GUI
5. Select the appropriate server file
6. Start the server

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 01/02/2023 00:25:53)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

226A6D882E929D5C38BEA37A5220B34D

Game version 0.20.16.1 (ReleaseLinux, branch master, revision 5807900)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Lua For Barotrauma, Lua Linker, EK | Utility, EK | Dockyard, EK | Gunnery, EK | Armory, Zubtrauma (Dialog Only), Combinable Ammo Revived (NOW WORKS WITH ALL AMMO), BaroCraftables+, Movable and Sellable Wrecks, New Wrecks For Barotrauma (With sellable wrecks), Basic1, EK Berith Mk-IV, EK Nurse Shark Mk-VI, Bambara EK, EK Marauder Mk-VII, EK Gladius Mk-II, EK_Crystal, EK Kira Mk-V
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Unix 6.1.1.1 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: ChildServerRelay readTask did not run to completion: status was WaitingForActivation. (System.Exception)
Target site: Barotrauma.Option`1[System.Int32] ReadIncomingMsgs()
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Networking/ChildServerRelay.cs:line 155
   at Barotrauma.Networking.ChildServerRelay.<UpdateRead>g__readBytes|43_0(Span`1 readTo) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Networking/ChildServerRelay.cs:line 183
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Networking/ChildServerRelay.cs:line 175

Last debug messages:
[01/02/2023 00:25:53] Exiting...
[01/02/2023 00:25:38] Failed to start server {An error occurred trying to start process './/home/m/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2559634234/Binary/DedicatedServer.exe' with working directory '/home/m/Drives/HUGE/SteamLibrary/steamapps/common/Barotrauma'. No such file or directory}
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Barotrauma.Networking.ChildServerRelay.Start(ProcessStartInfo processInfo) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/ChildServerRelay.cs:line 32
   at Barotrauma.MainMenuScreen.StartServer() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/MainMenuScreen.cs:line 945
[01/02/2023 00:25:38] Failed to start ChildServerRelay Process. File: .//home/m/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2559634234/Binary/DedicatedServer.exe, arguments: -name [removed] -public True -playstyle Casual -banafterwrongpassword False -karmaenabled False -maxplayers 16 -password [removed] -steamid [removed] -ownerkey [removed] -pipes 265 268
[01/02/2023 00:17:13] Attempting to open ALC device "Easy Effects Sink"
```

**Comment by evilfactory** [comment]
You are supposed to select the vanilla executable, not the Lua For Barotrauma one, as the vanilla executable is now the Lua one since you manually installed
