### ISSUE TITLE
Please make searching of filelist.xml case insensivity for linux

### ISSUE THREAD

**Issue by pavel4win** [evilfactory/LuaCsForBarotrauma#126]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In linux in time of initialization lua crashes if filelist.xml in mod folder was named as Filelist.xml
Issued for mods 
2855733204
2908606449

### Reproduction steps

1. use linux dedicated barotrauma server
2. load from workshop mods 2855733204 or 2908606449
3. try to start dedicated barotrauma server
4. see exception

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
[03/28/2023 18:59:36]
  Starting the server...
[03/28/2023 18:59:36]
  Using Lidgren networking. Manual port forwarding may be required. If players cannot connect to the server, you may want to use the in-game hosting menu (which uses SteamP2P networking and does not require port forwarding).
Lua! Version cf88aa4
Using LuaSetup.lua from the Barotrauma Lua/ folder.
[SV LUA ERROR] /home/steam/.steam/steamapps/common/Barotrauma Dedicated Server/Lua/ModLoader.lua:(128,12-59): Not a directory : '/home/steam/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2855733204/Filelist.xml': MoonSharp.Interpreter.NetRuntimeException: Not a directory : '/home/steam/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2855733204/Filelist.xml'
 ---> System.IO.IOException: Not a directory : '/home/steam/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2855733204/Filelist.xml'
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserEntries(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFileSystemEntries(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFileSystemEntries(String path)
   at Barotrauma.ToolBox.CorrectFilenameCase(String filename, Boolean& corrected, String directory) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Barotrauma/BarotraumaShared/SharedSource/Utils/ToolBox.cs:line 90
   at Barotrauma.ToolBox.CleanUpPathCrossPlatform(String path, Boolean correctFilenameCase, String directory) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Barotrauma/BarotraumaShared/SharedSource/Utils/ToolBox.cs:line 619
   at Barotrauma.ToolBox.CleanUpPath(String path) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Barotrauma/BarotraumaShared/SharedSource/Utils/ToolBox.cs:line 636
   at Barotrauma.LuaCsFile.<CanReadFromPath>g__getFullPath|0_0(String p) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Barotrauma/BarotraumaShared/SharedSource/LuaCs/LuaCsUtility.cs:line 20
   at Barotrauma.LuaCsFile.CanReadFromPath(String path) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Barotrauma/BarotraumaShared/SharedSource/LuaCs/LuaCsUtility.cs:line 22
   at Barotrauma.LuaCsFile.IsPathAllowedException(String path, Boolean write, LuaCsMessageOrigin origin) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Barotrauma/BarotraumaShared/SharedSource/LuaCs/LuaCsUtility.cs:line 98
   at Barotrauma.LuaCsFile.DirectoryExists(String path) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Barotrauma/BarotraumaShared/SharedSource/LuaCs/LuaCsUtility.cs:line 182
   at lambda_method16(Closure , Object , Object[] )
   at MoonSharp.Interpreter.Interop.MethodMemberDescriptor.Execute(Script script, Object obj, ScriptExecutionContext context, CallbackArguments args) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Interop/StandardDescriptors/ReflectionMemberDescriptors/MethodMemberDescriptor.cs:line 191
   at MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor.<>c__DisplayClass33_0.<GetCallback>b__0(ScriptExecutionContext context, CallbackArguments args) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Interop/StandardDescriptors/ReflectionMemberDescriptors/OverloadedMethodMemberDescriptor.cs:line 426
   at MoonSharp.Interpreter.CallbackFunction.Invoke(ScriptExecutionContext executionContext, IList`1 args, Boolean isMethodCall) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/DataTypes/CallbackFunction.cs:line 58
   at MoonSharp.Interpreter.Execution.VM.Processor.Internal_ExecCall(Int32 argsCount, Int32 instructionPtr, CallbackFunction handler, CallbackFunction continuation, Boolean thisCall, String debugText, DynValue unwindHandler) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Execution/VM/Processor/Processor_InstructionLoop.cs:line 723
   at MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Execution/VM/Processor/Processor_InstructionLoop.cs:line 116
   --- End of inner exception stack trace ---
   at MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Execution/VM/Processor/Processor_InstructionLoop.cs:line 307
   at MoonSharp.Interpreter.Execution.VM.Processor.Call(DynValue function, DynValue[] args) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Execution/VM/Processor/Processor.cs:line 85
   at MoonSharp.Interpreter.Script.Call(DynValue function, DynValue[] args) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Script.cs:line 474
   at Barotrauma.LuaRequire.ExecuteModule(String moduleName, Table environment, DynValue& returnValue) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Barotrauma/BarotraumaShared/SharedSource/LuaCs/Lua/LuaRequire.cs:line 85
   at Barotrauma.LuaRequire.Require(String moduleName, Table globalContext) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Barotrauma/BarotraumaShared/SharedSource/LuaCs/Lua/LuaRequire.cs:line 103
   at lambda_method3(Closure , Object , Object[] )
   at MoonSharp.Interpreter.Interop.MethodMemberDescriptor.Execute(Script script, Object obj, ScriptExecutionContext context, CallbackArguments args) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Interop/StandardDescriptors/ReflectionMemberDescriptors/MethodMemberDescriptor.cs:line 191
   at MoonSharp.Interpreter.Interop.FunctionMemberDescriptorBase.<>c__DisplayClass29_0.<GetCallback>b__0(ScriptExecutionContext c, CallbackArguments a) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Interop/StandardDescriptors/MemberDescriptors/FunctionMemberDescriptorBase.cs:line 83
   at MoonSharp.Interpreter.CallbackFunction.Invoke(ScriptExecutionContext executionContext, IList`1 args, Boolean isMethodCall) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/DataTypes/CallbackFunction.cs:line 58
   at MoonSharp.Interpreter.Execution.VM.Processor.Internal_ExecCall(Int32 argsCount, Int32 instructionPtr, CallbackFunction handler, CallbackFunction continuation, Boolean thisCall, String debugText, DynValue unwindHandler) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Execution/VM/Processor/Processor_InstructionLoop.cs:line 723
   at MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Execution/VM/Processor/Processor_InstructionLoop.cs:line 116
   at MoonSharp.Interpreter.Execution.VM.Processor.Call(DynValue function, DynValue[] args) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Execution/VM/Processor/Processor.cs:line 85
   at MoonSharp.Interpreter.Script.Call(DynValue function, DynValue[] args) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Script.cs:line 474
   at MoonSharp.Interpreter.Script.Call(Object function, Object[] args) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Libraries/moonsharp/MoonSharp.Interpreter/Script.cs:line 516
   at Barotrauma.LuaCsSetup.CallLuaFunction(Object function, Object[] args) in /home/runner/work/LuaCsForBarotrauma/LuaCsForBarotrauma/Barotrauma/BarotraumaShared/SharedSource/LuaCs/LuaCsSe
                                                                                                        

[SV LUA ERROR] /home/steam/.steam/steamapps/common/Barotrauma Dedicated Server/Lua/ModLoader.lua:(128,12-59): Not a directory : '/home/steam/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2908606449/Filelist.xml': MoonSharp.Interpreter.NetRuntimeException: Not a directory : '/home/steam/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2908606449/Filelist.xml'
 ---> System.IO.IOException: Not a directory : '/home/steam/.local/share/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2908606449/Filelist.xml'
```

**Comment by evilfactory** [comment]
This is already fixed in dev
