### ISSUE TITLE
Manual installation on Mac OS is error prone

### ISSUE THREAD

**Issue by ciriousjoker** [evilfactory/LuaCsForBarotrauma#145]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When installing the mod via [this tutorial](https://evilfactory.github.io/LuaCsForBarotrauma/lua-docs/manual/installing-lua-for-barotrauma-manually/) on mac os ventura, copying the mod files into the game folder corrupts the game and it will crash on launch.

Reason:
On mac os, because Apple ThiNKs DifFeReNtlY, pasting a folder with the same name as an existing folder will not merge them. Instead, the new folder will replace the existing folder.

Therefore, I needed to copy the Effects manually into the lowest folder.

I don't think mods caused this, since the Content folder was full at the start and basically empty at the end (only Effects folder)

### Reproduction steps

1. Install game
2. Paste mod files
3. Select "replace" and "apply to all" checkbox
4. Launch game (will crash)

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 07/08/2023 16:53:30)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

A2FB4D0B2331CB3A827C58811BB9F1F8

Game version 1.0.21.0 (ReleaseMac, branch master, revision 6b149e0)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Unix 13.4.1 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Could not find file '/Users/ciriousjoker/Library/Application Support/Steam/steamapps/common/Barotrauma/Barotrauma.app/Contents/MacOS/Content/Effects/waterbump.png'. (System.IO.FileNotFoundException)
Target site: Void ThrowExceptionForIoErrno(ErrorInfo, System.String, Boolean, System.Func`2[Interop+ErrorInfo,Interop+ErrorInfo])
Stack trace: 
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/SafeIO.cs:line 410
   at Barotrauma.IO.File.OpenRead(String path) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/SafeIO.cs:line 415
   at Barotrauma.TextureLoader.FromFile(String path, Boolean compress, Boolean mipmap) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Utils/TextureLoader.cs:line 193
   at Barotrauma.WaterRenderer..ctor(GraphicsDevice graphicsDevice) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Map/Levels/WaterRenderer.cs:line 71
   at Barotrauma.GameMain.LoadContent() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 407
   at Microsoft.Xna.Framework.Game.Initialize() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 551
   at Barotrauma.GameMain.Initialize() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 375
   at Microsoft.Xna.Framework.Game.DoInitialize() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 678
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 381
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58

Last debug messages:
[07/08/2023 16:53:29] Logged in as CiriousJoker (SteamID STEAM_1:0:57289487)
```

**Comment by evilfactory** [comment]
What do you suggest? Adding a note about MacOS replacing folders instead of merging on the tutorial?

**Comment by ciriousjoker** [comment]
Yes, perhaps splitting them into two instructions "copy all top level files" and "copy the content of Content/Effects into the Content/Effects folder".

I can't think of another solution here aside from writing some sort of "installation script" but that's overkill.

**Comment by evilfactory** [comment]
I just realized that the patches don't include the Content folder at all, did you accidentally download the build instead of a patch?

**Comment by ciriousjoker** [comment]
I'm stupid. Yes I did, this can be closed.
